import os
import re
from pathlib import Path
import pandas as pd
import numpy as np
from backend.app.config import settings

def run_profiling():
    dataset_dir = settings.DATASET_PATH
    output_doc = settings.PROJECT_ROOT / "docs" / "data_profiling_report.md"
    output_doc.parent.mkdir(parents=True, exist_ok=True)

    print(f"Profiling raw Zomato dataset from: {dataset_dir}")

    # Load datasets
    users = pd.read_csv(dataset_dir / "users.csv", low_memory=False)
    restaurants = pd.read_csv(dataset_dir / "restaurant.csv", low_memory=False)
    orders = pd.read_csv(dataset_dir / "orders.csv", low_memory=False)
    menu = pd.read_csv(dataset_dir / "menu.csv", low_memory=False)
    food = pd.read_csv(dataset_dir / "food.csv", low_memory=False)

    tables = {
        "users.csv": users,
        "restaurant.csv": restaurants,
        "orders.csv": orders,
        "menu.csv": menu,
        "food.csv": food,
    }

    report_lines = [
        "# Zomato Dataset Profiling & Exploratory Data Analysis Report",
        "",
        "> **Generated by:** DWDM Capstone Automated Profiler (`etl/profiling.py`)  ",
        f"> **Source Directory:** `{dataset_dir}`  ",
        f"> **Total Tables Analyzed:** {len(tables)}",
        "",
        "---",
        "",
        "## 1. Table & Column Inventory",
        "",
        "| Table Name | Total Rows | Total Columns | Memory (MB) | Primary Identifier |",
        "| :--- | :--- | :--- | :--- | :--- |",
    ]

    for name, df in tables.items():
        mem = df.memory_usage(deep=True).sum() / (1024 * 1024)
        pk = "user_id" if "user_id" in df.columns else ("id" if "id" in df.columns else ("f_id" if "f_id" in df.columns and name == "food.csv" else ("menu_id" if "menu_id" in df.columns else "Synthetic order_id")))
        report_lines.append(f"| `{name}` | {len(df):,} | {len(df.columns)} | {mem:.2f} MB | `{pk}` |")

    report_lines.extend([
        "",
        "---",
        "",
        "## 2. Deep Column-Level Schema & Null Analysis",
        "",
    ])

    for name, df in tables.items():
        report_lines.extend([
            f"### Table: `{name}`",
            "",
            "| Column Name | Inferred Dtype | Non-Null Count | Null Count | Null % | Unique Values | Sample Value |",
            "| :--- | :--- | :--- | :--- | :--- | :--- | :--- |",
        ])
        for col in df.columns:
            non_null = df[col].notnull().sum()
            null_cnt = df[col].isnull().sum()
            null_pct = (null_cnt / len(df)) * 100
            n_unique = df[col].nunique()
            sample = str(df[col].dropna().iloc[0]) if non_null > 0 else "N/A"
            # Truncate sample
            sample_clean = sample.replace("\n", " ").replace("|", "\\|")[:35]
            report_lines.append(f"| `{col}` | `{df[col].dtype}` | {non_null:,} | {null_cnt:,} | {null_pct:.2f}% | {n_unique:,} | `{sample_clean}` |")
        report_lines.append("")

    # Referential Integrity & Relationship Analysis
    report_lines.extend([
        "---",
        "",
        "## 3. Referential Integrity & Foreign Key Analysis",
        "",
        "| Relationship | Parent Key (Total) | Child Foreign Key (Total) | Valid References | Missing / Orphaned FKs | Status |",
        "| :--- | :--- | :--- | :--- | :--- | :--- |",
    ])

    # Orders -> Users
    valid_users = orders['user_id'].isin(users['user_id']).sum()
    orphaned_users = len(orders) - valid_users
    report_lines.append(f"| `orders.user_id` → `users.user_id` | {users['user_id'].nunique():,} users | {orders['user_id'].nunique():,} active users | {valid_users:,} ({valid_users/len(orders)*100:.1f}%) | {orphaned_users:,} | {'✅ 100% Integrity' if orphaned_users == 0 else '⚠️ Needs Cleaning'} |")

    # Orders -> Restaurants
    orders_clean_r = orders['r_id'].dropna().astype(int)
    valid_rest = orders_clean_r.isin(restaurants['id']).sum()
    null_rest_in_orders = orders['r_id'].isnull().sum()
    orphaned_rest = (len(orders_clean_r) - valid_rest) + null_rest_in_orders
    report_lines.append(f"| `orders.r_id` → `restaurant.id` | {restaurants['id'].nunique():,} restaurants | {orders['r_id'].nunique():,} ordered restaurants | {valid_rest:,} ({valid_rest/len(orders)*100:.1f}%) | {orphaned_rest:,} ({null_rest_in_orders} nulls) | ⚠️ Impute Default SK |")

    # Menu -> Restaurants
    valid_menu_r = menu['r_id'].isin(restaurants['id']).sum()
    orphaned_menu_r = len(menu) - valid_menu_r
    report_lines.append(f"| `menu.r_id` → `restaurant.id` | {restaurants['id'].nunique():,} restaurants | {menu['r_id'].nunique():,} restaurants | {valid_menu_r:,} ({valid_menu_r/len(menu)*100:.1f}%) | {orphaned_menu_r:,} | {'✅ 100% Integrity' if orphaned_menu_r == 0 else '⚠️ Needs Cleaning'} |")

    # Menu -> Food
    valid_menu_f = menu['f_id'].isin(food['f_id']).sum()
    orphaned_menu_f = len(menu) - valid_menu_f
    report_lines.append(f"| `menu.f_id` → `food.f_id` | {food['f_id'].nunique():,} food items | {menu['f_id'].nunique():,} menu dishes | {valid_menu_f:,} ({valid_menu_f/len(menu)*100:.1f}%) | {orphaned_menu_f:,} | {'✅ 100% Integrity' if orphaned_menu_f == 0 else '⚠️ Needs Cleaning'} |")

    # Business Anomalies & Data Quality Findings
    neg_amounts = (orders['sales_amount'] < 0).sum()
    zero_amounts = (orders['sales_amount'] == 0).sum()
    pos_amounts = (orders['sales_amount'] > 0).sum()

    orders['parsed_date'] = pd.to_datetime(orders['order_date'], errors='coerce')
    min_date = orders['parsed_date'].min().strftime('%Y-%m-%d')
    max_date = orders['parsed_date'].max().strftime('%Y-%m-%d')

    user_order_freq = orders['user_id'].value_counts()
    active_users = len(user_order_freq)
    dormant_users = len(users) - active_users

    report_lines.extend([
        "",
        "---",
        "",
        "## 4. Key Data Quality Anomalies & ETL Transformation Rules",
        "",
        "### A. Orders Table Cleaning",
        f"- **Date Range:** `{min_date}` to `{max_date}` (Total span: ~2.7 years).",
        f"- **Negative Sales Amounts:** `{neg_amounts:,}` rows ({neg_amounts/len(orders)*100:.2f}%) contain `sales_amount = -1`. These represent refund/canceled transactions and will be flagged/filtered during ETL.",
        f"- **Positive Valid Orders:** `{pos_amounts:,}` rows with positive monetary values.",
        f"- **Missing Restaurant IDs:** `{orders['r_id'].isnull().sum():,}` null `r_id` values. Imputed to `restaurant_sk = 0` (Unknown Restaurant) to preserve transaction counts.",
        "",
        "### B. Customer Inactivity & Churn Distribution",
        f"- **Total Registered Users:** `{len(users):,}`",
        f"- **Active Ordering Users:** `{active_users:,}` ({active_users/len(users)*100:.1f}%)",
        f"- **Dormant / Zero-Order Users:** `{dormant_users:,}` ({dormant_users/len(users)*100:.1f}%)",
        f"- **Order Frequency:** Mean `{user_order_freq.mean():.2f}` orders/active user (Min: 1, Median: 2, Max: 9).",
        "",
        "### C. Restaurant Cost & Rating Standardization",
        "- **Cost for Two Column:** Contains currency prefix characters (`₹ 200`, `₹ 1,200`). ETL will extract clean numeric floats.",
        "- **Ratings:** Contains non-numeric values (`--`, `NEW`, `Opening Soon`). Standardized to clean floats with default/imputed flags.",
        "- **Rating Counts:** Text strings like `'100+ ratings'`, `'Too Few Ratings'`. Standardized to integer counts.",
        "",
        "---",
        "",
        "## 5. Proposed Star Schema Mapping",
        "",
        "```",
        "  +-------------------+       +--------------------+",
        "  |     DIM_USER      |       |   DIM_RESTAURANT   |",
        "  |-------------------|       |--------------------|",
        "  | PK user_sk        |       | PK restaurant_sk   |",
        "  |    user_id        |       |    restaurant_id   |",
        "  |    name           |       |    name, city      |",
        "  |    age, gender    |       |    rating, cost    |",
        "  |    income, family |       |    primary_cuisine |",
        "  +---------+---------+       +---------+----------+",
        "            |                           |",
        "            +-------------+-------------+",
        "                          |",
        "                          v",
        "                +--------------------+",
        "                |    FACT_ORDERS     |",
        "                |--------------------|",
        "                | PK order_sk        |",
        "                | FK user_sk         |",
        "                | FK restaurant_sk   |",
        "                | FK date_sk         |",
        "                | FK location_sk     |",
        "                |    sales_qty       |",
        "                |    sales_amount    |",
        "                |    is_valid_order  |",
        "                +---------+----------+",
        "                          |",
        "            +-------------+-------------+",
        "            |                           |",
        "            v                           v",
        "  +-------------------+       +--------------------+",
        "  |     DIM_DATE      |       |    DIM_LOCATION    |",
        "  |-------------------|       |--------------------|",
        "  | PK date_sk        |       | PK location_sk     |",
        "  |    full_date      |       |    city            |",
        "  |    year, quarter  |       |    tier            |",
        "  |    month, day     |       +--------------------+",
        "  +-------------------+",
        "```",
    ])

    with open(output_doc, "w", encoding="utf-8") as f:
        f.write("\n".join(report_lines))

    print(f"Data profiling report successfully written to: {output_doc}")
    return output_doc

if __name__ == "__main__":
    run_profiling()
